/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Store;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author hii
 */
public class custbill extends javax.swing.JFrame {
    int i=0 ;
    /**
     * Creates new form custbill
     */
    bill b = new bill();
    ArrayList<Product> pro = new ArrayList<>();
    ArrayList<Product> buyPro = new ArrayList<>();
    proddatabase p;

    public custbill() throws Exception {
        initComponents();
        setTitle("ASM Super Store");
        setIconImage(new ImageIcon("Cash_Register.png").getImage());
        proddatabase p = new proddatabase();
        p.Connect();
        pro = p.getProdata();

    }

    public void setDefaultCloseOperation(int operation) {
        super.setDefaultCloseOperation(HIDE_ON_CLOSE); //To change body of generated methods, choose Tools | Templates.

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Formpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        quantityl = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        namel = new javax.swing.JLabel();
        Quantity = new javax.swing.JTextField();
        More = new javax.swing.JButton();
        Update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Formpanel.setBackground(new java.awt.Color(255, 255, 255));
        Formpanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Goudy Stout", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bill Entry Form");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 98, 0, 121);
        Formpanel.add(jLabel1, gridBagConstraints);

        quantityl.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        quantityl.setForeground(new java.awt.Color(102, 0, 102));
        quantityl.setText("Quantity");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 203, 0, 0);
        Formpanel.add(quantityl, gridBagConstraints);

        Id.setBackground(new java.awt.Color(102, 0, 102));
        Id.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Id.setForeground(new java.awt.Color(255, 255, 255));
        Id.setAutoscrolls(false);
        Id.setCaretColor(new java.awt.Color(255, 255, 255));
        Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 128;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        Formpanel.add(Id, gridBagConstraints);

        namel.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        namel.setForeground(new java.awt.Color(102, 0, 102));
        namel.setText("Product Id");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 182, 0, 0);
        Formpanel.add(namel, gridBagConstraints);

        Quantity.setBackground(new java.awt.Color(102, 0, 102));
        Quantity.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Quantity.setForeground(new java.awt.Color(255, 255, 255));
        Quantity.setAutoscrolls(false);
        Quantity.setCaretColor(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 129;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 0, 0);
        Formpanel.add(Quantity, gridBagConstraints);

        More.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        More.setForeground(new java.awt.Color(102, 0, 102));
        More.setText("More");
        More.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        More.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoreActionPerformed(evt);
            }
        });
        More.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MoreKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 257, 0, 0);
        Formpanel.add(More, gridBagConstraints);

        Update.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Update.setForeground(new java.awt.Color(102, 0, 102));
        Update.setText("Make Bill");
        Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 257, 33, 0);
        Formpanel.add(Update, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Formpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Formpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoreActionPerformed
        // TODO add your handling code here:
        int q = 1 ;
        if (Quantity.getText().compareToIgnoreCase("")==1)
            q =Integer.parseInt(Quantity.getText());
                
        try {
            getPrice(Integer.parseInt(Id.getText()), q);
        } catch (Exception ex) {
            Logger.getLogger(custbill.class.getName()).log(Level.SEVERE, null, ex);
        }
        Id.setText("");
        Quantity.setText("");
        i++ ;

    }//GEN-LAST:event_MoreActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        for (Product buyPro1 : buyPro) {
            b.p += buyPro1.getPrice() * buyPro1.getStock();
        }
        b.bill.setText(String.valueOf(b.p));
        b.setVisible(true);
      //  b.c.t_amount = b.p ;
        
    }//GEN-LAST:event_UpdateActionPerformed

    private void IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdActionPerformed

    private void MoreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MoreKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_MoreKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(custbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(custbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(custbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(custbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new custbill().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(custbill.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    void getPrice(int id, int q) throws Exception {
       
        for (Product pro1 : pro) {
            
            if (id == pro1.getId()) {
 

                    buyPro.add(pro1);
                    buyPro.get(i).setStock(q);
                    System.out.println(pro1);
               }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Formpanel;
    private javax.swing.JTextField Id;
    private javax.swing.JButton More;
    private javax.swing.JTextField Quantity;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel namel;
    private javax.swing.JLabel quantityl;
    // End of variables declaration//GEN-END:variables
}
