/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Store;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

/**
 *
 * @author hii
 */
public class productform extends javax.swing.JFrame {

    /**
     * Creates new form productform
     */
    proddatabase p;
    revDatabase rev = new revDatabase();

    public productform() throws Exception {
        initComponents();
        setTitle("ASM super Store");
        setIconImage(new ImageIcon("wal.jpg").getImage());
        Add.setVisible(false);
        setPrce.setVisible(false);
        setstock.setVisible(false);
        id.setVisible(false);
        jLabel2.setVisible(false);
        p = new proddatabase();

    }

    @Override
    public void setDefaultCloseOperation(int operation) {
        super.setDefaultCloseOperation(HIDE_ON_CLOSE); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Formpanel = new javax.swing.JPanel();
        Price = new javax.swing.JTextField();
        Type = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        quantityl = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        namel = new javax.swing.JLabel();
        Pricel = new javax.swing.JLabel();
        supp = new javax.swing.JLabel();
        Quantity = new javax.swing.JTextField();
        Subtype = new javax.swing.JTextField();
        Supplier = new javax.swing.JTextField();
        Subtypel = new javax.swing.JLabel();
        Typel = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        setPrce = new javax.swing.JButton();
        setstock = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(560, 450));

        Formpanel.setBackground(new java.awt.Color(255, 255, 255));
        Formpanel.setEnabled(false);
        Formpanel.setLayout(new java.awt.GridBagLayout());

        Price.setBackground(new java.awt.Color(102, 0, 102));
        Price.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Price.setForeground(new java.awt.Color(255, 255, 255));
        Price.setCaretColor(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 128;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 11, 0, 0);
        Formpanel.add(Price, gridBagConstraints);

        Type.setBackground(new java.awt.Color(102, 0, 102));
        Type.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Type.setForeground(new java.awt.Color(255, 255, 255));
        Type.setCaretColor(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 129;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        Formpanel.add(Type, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Goudy Stout", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Product Entry Form");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 20, 0, 0);
        Formpanel.add(jLabel1, gridBagConstraints);

        quantityl.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        quantityl.setForeground(new java.awt.Color(102, 0, 102));
        quantityl.setText("Quantity");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 114, 0, 0);
        Formpanel.add(quantityl, gridBagConstraints);

        Name.setBackground(new java.awt.Color(102, 0, 102));
        Name.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setCaretColor(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 128;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        Formpanel.add(Name, gridBagConstraints);

        namel.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        namel.setForeground(new java.awt.Color(102, 0, 102));
        namel.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 150, 0, 0);
        Formpanel.add(namel, gridBagConstraints);

        Pricel.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Pricel.setForeground(new java.awt.Color(102, 0, 102));
        Pricel.setText("Price");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 156, 0, 0);
        Formpanel.add(Pricel, gridBagConstraints);

        supp.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        supp.setForeground(new java.awt.Color(102, 0, 102));
        supp.setText("Supplier");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 119, 0, 0);
        Formpanel.add(supp, gridBagConstraints);

        Quantity.setBackground(new java.awt.Color(102, 0, 102));
        Quantity.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Quantity.setForeground(new java.awt.Color(255, 255, 255));
        Quantity.setCaretColor(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 129;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 10, 0, 0);
        Formpanel.add(Quantity, gridBagConstraints);

        Subtype.setBackground(new java.awt.Color(102, 0, 102));
        Subtype.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Subtype.setForeground(new java.awt.Color(255, 255, 255));
        Subtype.setCaretColor(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 127;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        Formpanel.add(Subtype, gridBagConstraints);

        Supplier.setBackground(new java.awt.Color(102, 0, 102));
        Supplier.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Supplier.setForeground(new java.awt.Color(255, 255, 255));
        Supplier.setCaretColor(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 129;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 10, 0, 0);
        Formpanel.add(Supplier, gridBagConstraints);

        Subtypel.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Subtypel.setForeground(new java.awt.Color(102, 0, 102));
        Subtypel.setText("Sub-Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 98, 0, 0);
        Formpanel.add(Subtypel, gridBagConstraints);

        Typel.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Typel.setForeground(new java.awt.Color(102, 0, 102));
        Typel.setText("Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 157, 0, 0);
        Formpanel.add(Typel, gridBagConstraints);

        Update.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Update.setForeground(new java.awt.Color(102, 0, 102));
        Update.setText("Update");
        Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 41, 0, 0);
        Formpanel.add(Update, gridBagConstraints);

        Add.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Add.setForeground(new java.awt.Color(102, 0, 102));
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.ipady = -4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 41, 0, 0);
        Formpanel.add(Add, gridBagConstraints);

        setPrce.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        setPrce.setForeground(new java.awt.Color(102, 0, 102));
        setPrce.setText("SetPrice");
        setPrce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setPrceActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 41, 0, 26);
        Formpanel.add(setPrce, gridBagConstraints);

        setstock.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        setstock.setForeground(new java.awt.Color(102, 0, 102));
        setstock.setText("SetQuantity");
        setstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setstockActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 41, 0, 26);
        Formpanel.add(setstock, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 182, 0, 0);
        Formpanel.add(jLabel2, gridBagConstraints);

        id.setBackground(new java.awt.Color(102, 0, 102));
        id.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 128;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 10, 0, 0);
        Formpanel.add(id, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Formpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Formpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        try {
            // TODO add your handling code here:
            updatestck();
        } catch (Exception ex) {
            Logger.getLogger(productform.class.getName()).log(Level.SEVERE, null, ex);
        }

        setVisible(false);
    }//GEN-LAST:event_UpdateActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:

        String Nam = Name.getText();
        double price = Double.valueOf(Price.getText());
        String type = Type.getText();
        int quantity = Integer.parseInt(Quantity.getText());
        String subtype = Subtype.getText();
        String supp = Supplier.getText();
        try {
            p.Connect();
            p.insert(new Product(Nam, quantity, 1, price, type, subtype));
        } catch (SQLException ex) {
            Logger.getLogger(productform.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(productform.class.getName()).log(Level.SEVERE, null, ex);
        }
        clear();
    }//GEN-LAST:event_AddActionPerformed

    private void setstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setstockActionPerformed
        // TODO add your handling code here:
        int idp = Integer.parseInt(id.getText());
        int quan = Integer.parseInt(Quantity.getText());
        double price = 0;
        try {
            p.Connect();

            rev.Connect();
            ArrayList<Product> proo = p.getProdata();
            for (int i = 0; i < proo.size(); i++) {
                if (proo.get(i).getId() == idp) {
                    price = proo.get(i).getPrice();
                    p.editQuan(proo.get(i).getStock() + quan, idp);
                    break;
                }
            }
            ArrayList<MainRev> revlist = rev.getRevdata();
            rev.editPurc(revlist.get(revlist.size() - 1).t_buy + ((price * 0.90) * quan), 2);
        } catch (SQLException ex) {
            Logger.getLogger(productform.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(productform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_setstockActionPerformed

    private void setPrceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPrceActionPerformed
        // TODO add your handling code here:
        int idp = Integer.parseInt(id.getText());
        double price = Double.valueOf(Price.getText());
        try {
            p.Connect();
            p.editPrice(price, idp);

        } catch (Exception ex) {
            Logger.getLogger(productform.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_setPrceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new productform().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(productform.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    void getPro(Product p) {

        Name.setText(p.getName());
        Price.setText(String.valueOf(p.getPrice()));
        Type.setText(p.getType());
        Quantity.setText(String.valueOf(p.getStock()));
        Subtype.setText(p.getSubtype());
        Supplier.setText("");
        Name.setFocusable(false);
        Price.setFocusable(false);
        Type.setFocusable(false);
        Quantity.setFocusable(false);
        Subtype.setFocusable(false);
        Supplier.setFocusable(false);
    }

    void updatestck() throws Exception {
        int idp = Integer.parseInt(id.getText());
        String Nam = Name.getText();
        double price = Double.valueOf(Price.getText());
        String type = Type.getText();
        int quantity = Integer.parseInt(Quantity.getText());
        String subtype = Subtype.getText();
        String supp = Supplier.getText();
        try {
            p.Connect();
            p.editPro(new Product(Nam, quantity, idp, price, type, subtype));

        } catch (SQLException ex) {
            Logger.getLogger(productform.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(productform.class.getName()).log(Level.SEVERE, null, ex);
        }

        rev.Connect();
        ArrayList<MainRev> revlist = rev.getRevdata();
        rev.editPurc(revlist.get(revlist.size() - 1).t_buy + ((price * 0.90) * quantity), 2);
    }

    void clear() {

        Name.setText("");
        Price.setText("");
        Type.setText("");
        Quantity.setText("");
        Subtype.setText("");
        Supplier.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton Add;
    private javax.swing.JPanel Formpanel;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Price;
    private javax.swing.JLabel Pricel;
    private javax.swing.JTextField Quantity;
    private javax.swing.JTextField Subtype;
    private javax.swing.JLabel Subtypel;
    private javax.swing.JTextField Supplier;
    private javax.swing.JTextField Type;
    private javax.swing.JLabel Typel;
    javax.swing.JButton Update;
    javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    private javax.swing.JLabel namel;
    private javax.swing.JLabel quantityl;
    javax.swing.JButton setPrce;
    javax.swing.JButton setstock;
    private javax.swing.JLabel supp;
    // End of variables declaration//GEN-END:variables
}
