/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Store;

import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hii
 */
public class revview extends javax.swing.JPanel {

    /**
     * Creates new form revview
     */
    ArrayList<MainRev> rev = new ArrayList<>();

    public revview() throws Exception {
        initComponents();
        double paisee = 0 ;
        double exp = 0 ;
        setMinimumSize(new Dimension(900, 550));
        revDatabase r = new revDatabase();
        r.Connect();
    
        
        EmpDatabase e = new EmpDatabase();
        e.Connect();
        ArrayList<Employee> emp = e.getEmpdata();
        for(int i = 0 ; i < emp.size() ; i++)
        {
            exp+=emp.get(i).salary;
        
        
        }
        r.editExp(exp, 2);
        
        rev = r.getRevdata();
        for(int i = 0 ; i <rev.size(); i++)
        {
             paisee+= rev.get(i).profit;
        
        }
        paise.setText(String.valueOf(paisee));
        setdata();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        revv = new javax.swing.JPanel();
        reven = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        paise = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        revv.setBackground(new java.awt.Color(255, 255, 255));
        revv.setAutoscrolls(true);
        revv.setLayout(new java.awt.GridBagLayout());

        reven.setBackground(new java.awt.Color(255, 255, 255));
        reven.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Amount in Hand: ");
        reven.add(jLabel1);

        paise.setBackground(new java.awt.Color(255, 255, 255));
        paise.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        paise.setText("Rs:");
        reven.add(paise);

        revv.add(reven, new java.awt.GridBagConstraints());

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Month", "Total sell", "Profit", "Total Buy", "Expense"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setDragEnabled(true);
        jTable1.setFocusable(false);
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 842;
        gridBagConstraints.ipady = 438;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 11, 10);
        revv.add(jScrollPane1, gridBagConstraints);

        add(revv, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents
void setdata() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        for (int i = 0; i < rev.size(); i++) {

            Object[] row = {rev.get(i).month, rev.get(i).t_sell, rev.get(i).t_sell - rev.get(i).t_buy- rev.get(i).expense, rev.get(i).t_buy,rev.get(i).expense};

            model.addRow(row);

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel paise;
    private javax.swing.JPanel reven;
    javax.swing.JPanel revv;
    // End of variables declaration//GEN-END:variables
}
